import '../src/shared/styles/globals.scss';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import React from 'react';
import Header from '../src/shared/components/Header';
import AppWrapper from '../src/shared/components/AppWrapper/AppWrapper';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppWrapper>
        <Header />
        <Component {...pageProps} />
      </AppWrapper>
    </div>
  );
}

export default MyApp;
